name: Release

on:
  push:
    branches: ["main"]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get all tags

      - name: Download auto
        run: |
          curl -kL -o - https://github.com/intuit/auto/releases/download/v11.3.0/auto-linux.gz | gunzip > ${{ runner.temp }}/auto
          chmod +x ${{ runner.temp }}/auto

      - name: Release
        run: ${{ runner.temp }}/auto shipit --no-changelog --only-publish-with-release-label --name github-actions[bot] --email github-actions[bot]@users.noreply.github.com

      - name: Get next release number
        id: next_release
        run: echo "version=$(${{ runner.temp }}/auto shipit --dry-run --quiet --name github-actions[bot] --email github-actions[bot]@users.noreply.github.com)" >> $GITHUB_OUTPUT

      - name: Update changelog
        id: update_changelog
        run: |
          echo changes<<EOF
          ${{ runner.temp }}/auto changelog --quiet --no-git-commit --name github-actions[bot] --email github-actions[bot]@users.noreply.github.com 
          echo EOF >> $GITHUB_ENV
        if: steps.next_release.outputs.version != ''

      - name: Create versioning pull request
        uses: peter-evans/create-pull-request@v7
        if: steps.next_release.outputs.version != ''
        with:
          branch: auto/release
          title: Release version `${{ steps.next_release.outputs.version }}`
          commit-message: Release version `${{ steps.next_release.outputs.version }}`
          labels: release
          body: |
            This PR will release version `${{ steps.next_release.outputs.version }}` with the following changes:

            ${{ env.changes }}

            To release the version when you are ready, merge this PR.

            If you don't see your changes in the list above, please check your PR is tagged with an appropriate label to include your change in the release notes.
